services:
  db:
    image: postgres:14.5
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - admin
      - local-service
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PG_DATA: /data/postgres
  pgadmin:
    image: dpage/pgadmin4:6.13
    depends_on:
      - db
    container_name: pgadmin
    restart: always
    ports:
      - "9090:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
  nd-authentication:
    image: nd-authentication:latest
    depends_on:
      - db
    container_name: nd-authentication
    restart: always
    ports:
      - "9000:9000"
    networks:
      - local-service
  nd-appointment:
    image: nd-appointment:latest
    depends_on:
      - db
    container_name: nd-appointment
    restart: always
    ports:
      - "9001:9001"
    networks:
      - local-service
  nd-chat:
    image: nd-chat:latest
    depends_on:
      - db
    container_name: nd-chat
    restart: always
    ports:
      - "9002:9002"
    networks:
      - local-service

networks:
  admin:
    driver: bridge
  local-service:
    driver: bridge

volumes:
  postgres:
  pgadmin: