server:
  port: 9000

spring:
  application:
    name: authentication

  datasource:
    url: jdbc:postgresql://db:5432/telemedic_authentication
    username: 'admin'
    password: 'admin'

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

